server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      instance-id: gateway-9527.com
      prefer-ip-address: true #访问路径可显示ip地址     
zuul: 
  prefix: /pre #统一前缀管理
  ignored-services: "*" #忽略多个微服务serviceId
  routes:
    mydept.serviceId: microservicecloude-dept
    mydept.path: /mydept/**
 
info:
    app.name: microservicecloud-zuul
    company.name: www.gateway.com
    build.artifactId: ${project.artifactId}$
build.version: ${project.version}$
